name: Lint

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out LoRDraft
        uses: actions/checkout@v2
        with:
          path: LoRDraft
          submodules: recursive
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: '.'
          extensions: 'ts'
          clangFormatVersion: 15
